name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    environment: wincfarm

    steps:
      - uses: actions/checkout@v2

      - name: Restart webserver
        run: echo ${{ secret.SUDO_PWD }} | sudo -S systemctl restart wincfarm

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
